export const FETCH_INSTRUMENTS_AXIO = 'FETCH_INSTRUMENTS_AXIO';
export const FETCH_INSTRUMENTS = 'FETCH_INSTRUMENTS';
export const REQUEST_INSTRUMENTS = 'REQUEST_INSTRUMENTS';
export const RECIEVE_INSTRUMENTS = 'RECIEVE_INSTRUMENTS';
export const BOOK_SELECTED = 'BOOK_SELECTED';
export const REQUEST_EXCHANGE_CURRENCY = 'REQUEST_EXCHANGE_CURRENCY';
